package com.ian.app.drinkings.core.domain.model.mapper

import com.ian.app.drinkings.core.data.local.entity.EntityDetailNonAlcoholDrink
import com.ian.app.drinkings.core.data.remote.api.ResponseDetailNonAlcoholDrink
import com.ian.app.drinkings.core.domain.model.DetailNonAlcoholDrink

fun ResponseDetailNonAlcoholDrink.mapRemoteNonAlcoholDrinkToDomain(): DetailNonAlcoholDrink {
    return DetailNonAlcoholDrink(
        remoteIdDrink = idDrink,
        strDrink = strDrink,
        strDrinkAlternate = strDrinkAlternate,
        strCategory = strCategory,
        strArea = strArea,
        strInstructions = strInstructions,
        strDrinkThumb = strDrinkThumb,
        strImageSource = strImageSource,
        strIngredient1 = strIngredient1,
        strIngredient2 = strIngredient2,
        strIngredient3 = strIngredient3,
        strIngredient4 = strIngredient4,
        strIngredient5 = strIngredient5,
        strIngredient6 = strIngredient6,
        strIngredient7 = strIngredient7,
        strIngredient8 = strIngredient8,
        strIngredient9 = strIngredient9,
        strIngredient10 = strIngredient10,
        strIngredient11 = strIngredient11,
        strIngredient12 = strIngredient12,
        strIngredient13 = strIngredient13,
        strIngredient14 = strIngredient14,
        strIngredient15 = strIngredient15,
        strMeasure1 = strMeasure1,
        strMeasure2 = strMeasure2,
        strMeasure3 = strMeasure3,
        strMeasure4 = strMeasure4,
        strMeasure5 = strMeasure5,
        strMeasure6 = strMeasure6,
        strMeasure7 = strMeasure7,
        strMeasure8 = strMeasure8,
        strMeasure9 = strMeasure9,
        strMeasure10 = strMeasure10,
        strMeasure11 = strMeasure11,
        strMeasure12 = strMeasure12,
        strMeasure13 = strMeasure13,
        strMeasure14 = strMeasure14,
        strMeasure15 = strMeasure15,
    )
}

fun EntityDetailNonAlcoholDrink.mapLocalNonAlcoholDrinkToDomain(): DetailNonAlcoholDrink {
    return DetailNonAlcoholDrink(
        remoteIdDrink = remoteIdDrink,
        strDrink = strDrink,
        strDrinkAlternate = strDrinkAlternate,
        strCategory = strCategory,
        strArea = strArea,
        strInstructions = strInstructions,
        strDrinkThumb = strDrinkThumb,
        strImageSource = strImageSource,
        strIngredient1 = strIngredient1,
        strIngredient2 = strIngredient2,
        strIngredient3 = strIngredient3,
        strIngredient4 = strIngredient4,
        strIngredient5 = strIngredient5,
        strIngredient6 = strIngredient6,
        strIngredient7 = strIngredient7,
        strIngredient8 = strIngredient8,
        strIngredient9 = strIngredient9,
        strIngredient10 = strIngredient10,
        strIngredient11 = strIngredient11,
        strIngredient12 = strIngredient12,
        strIngredient13 = strIngredient13,
        strIngredient14 = strIngredient14,
        strIngredient15 = strIngredient15,
        strMeasure1 = strMeasure1,
        strMeasure2 = strMeasure2,
        strMeasure3 = strMeasure3,
        strMeasure4 = strMeasure4,
        strMeasure5 = strMeasure5,
        strMeasure6 = strMeasure6,
        strMeasure7 = strMeasure7,
        strMeasure8 = strMeasure8,
        strMeasure9 = strMeasure9,
        strMeasure10 = strMeasure10,
        strMeasure11 = strMeasure11,
        strMeasure12 = strMeasure12,
        strMeasure13 = strMeasure13,
        strMeasure14 = strMeasure14,
        strMeasure15 = strMeasure15,
    )
}

fun DetailNonAlcoholDrink.mapNonAlcoholDrinkToData(): EntityDetailNonAlcoholDrink {
    return EntityDetailNonAlcoholDrink(
        localDrinkId = null,
        remoteIdDrink = remoteIdDrink,
        strDrink = strDrink,
        strDrinkAlternate = strDrinkAlternate,
        strCategory = strCategory,
        strArea = strArea,
        strInstructions = strInstructions,
        strDrinkThumb = strDrinkThumb,
        strImageSource = strImageSource,
        strIngredient1 = strIngredient1,
        strIngredient2 = strIngredient2,
        strIngredient3 = strIngredient3,
        strIngredient4 = strIngredient4,
        strIngredient5 = strIngredient5,
        strIngredient6 = strIngredient6,
        strIngredient7 = strIngredient7,
        strIngredient8 = strIngredient8,
        strIngredient9 = strIngredient9,
        strIngredient10 = strIngredient10,
        strIngredient11 = strIngredient11,
        strIngredient12 = strIngredient12,
        strIngredient13 = strIngredient13,
        strIngredient14 = strIngredient14,
        strIngredient15 = strIngredient15,
        strMeasure1 = strMeasure1,
        strMeasure2 = strMeasure2,
        strMeasure3 = strMeasure3,
        strMeasure4 = strMeasure4,
        strMeasure5 = strMeasure5,
        strMeasure6 = strMeasure6,
        strMeasure7 = strMeasure7,
        strMeasure8 = strMeasure8,
        strMeasure9 = strMeasure9,
        strMeasure10 = strMeasure10,
        strMeasure11 = strMeasure11,
        strMeasure12 = strMeasure12,
        strMeasure13 = strMeasure13,
        strMeasure14 = strMeasure14,
        strMeasure15 = strMeasure15,

    )
}
