package com.ian.app.drinkings.model

import com.ian.app.drinkings.data.remote.api.ResponseAlcoholDrink
import com.ian.app.drinkings.data.remote.api.ResponseNonAlcoholDrink

object DummyResponse {
    val DUMMY_ALCOHOL: ResponseAlcoholDrink = ResponseAlcoholDrink(
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a"
    )

    val DUMMY_NON_ALCOHOL: ResponseNonAlcoholDrink = ResponseNonAlcoholDrink(
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a"
    )
}
